# Generated by Django 6.0.3 on 2026-04-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_encargo_precio_usuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('CARRITO', 'En el Carrito'), ('PENDIENTE', 'Pendiente'), ('PREPARACION', 'En Preparación'), ('PROCESO', 'En Proceso'), ('ENVIADO', 'Enviado'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20),
        ),
    ]
