# Generated by Django 6.0.3 on 2026-04-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_encargo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('CARRITO', 'En el Carrito'), ('PENDIENTE', 'Pendiente'), ('PREPARACION', 'En Preparación'), ('PROCESO', 'En Proceso'), ('ENVIADO', 'Enviado'), ('FINALIZADO', 'Finalizado')], default='CARRITO', max_length=20),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='id_tejido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.tejido'),
        ),
    ]
