# Generated by Django 6.0.3 on 2026-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_encargo_options_alter_encargo_estado_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargo',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
