# Generated by Django 6.0.3 on 2026-04-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_encargo_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoImagen',
        ),
    ]
